### ISSUE TITLE
Deprecate Github Webhook creation feature

### ISSUE THREAD

**Issue by whynowy** [argoproj/argo-events#1112]
**Is your feature request related to a problem? Please describe.**
`GithubEventSource` provides a feature to set up a Github webhook when the event source starts, this actually brings some problems which are difficult to resolve.

- When creating the webhook in Github with `GithubEventSource`, as a user, the ingress (a LB Service or other kinds of ingress) for the event source is most probably not created yet (because no matter it's a LB Service or whatever ingress, you need to know the Pod Selector Labels to create it, the user doesn't know the labels before the EventSource Pod is in place unless he or she is very familiar with Argo EventS source code), so the URL to be configured in the GithubEventSource is still unknown.
-  Webhook creation is just a one time effort, it's very easy to configure it in Github Settings GUI, comparing with setting it up in the GUI, I don't believe most of the users prefer to configure a Kubernetes Secret for the API token, and let the GIthubEventSource do it.
- **[Fixed]** There's a bug currently in Argo Events source code. When the EventSource Pod starts, if the creating actions responds that the webhook is already existing, Argo Events tries to compare the URL and events from the existing webhook list with the configuration in the spec to find the existing one. Github stores the order of configured events, but the code doesn't sort and compare, so if you create the EventSource with `pull_request, push`, and then update the order to `push, pull_request`, it will cause to an error, it complains the webhook is already existing, but failed to find the webhook. 
- **[Fixed]** If the events list is something like `*, push, pull_request`, it actually create a webhook with `all_events`, and this brings another bug, the events list comparing again above always return false.
- Github allows same webhook URL to be configured multiple times, for example, `webhook1 (pull_request, push)` and `webhook2 (pull_request, create)` with same URL are valid. So if you create a GithubEventSource with `pull_request, push`, it creates a webhook, later on, you update the EventSource to only have `pull_request`, it creates another webhook. This is very tricky for Argo Events to handle this situation.

**Describe the solution you'd like**
1. Deprecate the webhook creating feature, the GithubEventSource would only be responsible for handling the post events from Github.
2. It doesn't care about what the repository is (or it does if a valid list is given).
3. Events config in the spec are still available, that only means what are the interested events types (event though Github already has the events configured), and the events config could be extended, such as pull_request of what branch, etc.

Typical operations of using GithubEventSource would be:

1. Create a GithubEventSource;
2. Create a LB Service (or other kinds of ingress) for the event source, you get the URL;
3. Configure a webhook in Github Settings GUI.

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by Hunter-Thompson** [comment]
We planned on using this feature to onboard an application to our ArgoStack by simply creating a PR to the master branch with a new entry in the `repositories` list in the Event config. (Feature requested #1091) 

Since ArgoCD is already listening for changes on the Event config, the webhook gets created instantly the moment the PR is merged. 

This allows developers to onboard their application without doing any manual webhook creation, and also allows for a self-serving CI/CD system.

**Comment by davidcollom** [comment]
We use this feature extensively, within our platform due to users being able to subscribe their repositories dynamically to be monitored for changes.

Due to security concerns we can't use a generic Webhook endpoint as we must have a Unique URI for each repository.

Having this feature allows/ensures that we can maintain configuration for our platform within one place rather spread across multiple repositories and maintain
