### ISSUE TITLE
Argo events triggering workflow continuously 

### ISSUE THREAD

**Issue by saiyidi** [argoproj/argo-events#1273]
We have a severe issue in PROD wherein the workflow which is part of a sensor is getting triggered without any control.
This is a bug since we deleted the sensor, event source and event bus but still it gets triggered. 
It spins indefinite amount of pods. 

The only way to stop this is to stop the workflow controller but once we bring that up, the pods start again.

Please help us with this issue as its quite a big blocker.

**Comment by saiyidi** [comment]
ime="2021-07-06T10:03:00.876Z" level=info authModes="[client]" baseHRef=/ managedNamespace=pga namespace=pga secure=false
time="2021-07-06T10:03:00.876Z" level=warning msg="You are running in insecure mode. Learn how to enable transport layer security: https://argoproj.github.io/argo/tls/"
time="2021-07-06T10:03:00.876Z" level=info msg="config map" name=workflow-controller-configmap
time="2021-07-06T10:03:00.876Z" level=info msg="SSO disabled"
time="2021-07-06T10:03:00.904Z" level=info msg="Starting Argo Server" instanceID= version=v2.12.10
time="2021-07-06T10:03:00.904Z" level=info msg="Creating event controller" operationQueueSize=16 workerCount=4
time="2021-07-06T10:03:00.906Z" level=info msg="Argo Server started successfully on http://localhost:2746"
time="2021-07-06T10:03:18.771Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListCronWorkflows grpc.service=cronworkflow.CronWorkflowService grpc.start_time="2021-07-06T10:03:18Z" grpc.time_ms=49.413 span.kind=server system=grpc
time="2021-07-06T10:03:18.797Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=ListWorkflowTemplates grpc.service=workflowtemplate.WorkflowTemplateService grpc.start_time="2021-07-06T10:03:18Z" grpc.time_ms=72.76 span.kind=server system=grpc
time="2021-07-06T10:03:18.849Z" level=info msg="finished unary call with code OK" grpc.code=OK grpc.method=GetVersion grpc.service=info.InfoService grpc.start_time="2021-07-06T10:03:18Z" grpc.time_ms=1.563 span.kind=server system=grpc

**Comment by whynowy** [comment]
From what you described, I guess:

1. There were many workflow objects got created before you deleting the Sensor object
2. The workflow-controller takes time to process those workflow objects, that's why you saw workflow pods still came up afterwards.

So, you need to do some investigation before raising an issue here:

1. Check if there are many workflow objects by either `argo list` or `kubectl get wf`, some of them might be in `pending` status, which means they are waiting to be processed by workflow-controller;
2. Check eventsource and sensor pod logs, to see if those events and workflow triggering actions were expected.
