### ISSUE TITLE
eventsource consume events from forked repo

### ISSUE THREAD

**Issue by MosenzonTal** [argoproj/argo-events#1439]
**Describe the bug**
i forked a repo for testing, configured the event source to trigger the sensor on every push. and after testing finished, i configured the event source repo: owner to the real one.
I attention that still pushes to the forked repo triggers the sensor.

**Expected behavior**
pushes to the fork repo shouldn't trigger the sensor to trigger a pipeline

**Environment (please complete the following information):**
 - Argo Events: [e.g. v1.0.0] argoproj.io/v1alpha1

**Comment by daniel-codefresh** [comment]
@MosenzonTal Just to clarify, are you getting events for both the forked repo and the upstream repo after the change?
It makes sense if you do, because you probably still have the old webhook configured on your forked repo from the old eventsource configuration. Old webhooks are not being deleted by Argo Events unless you have `deleteHookOnFinish` configured in your eventsource spec: https://github.com/argoproj/argo-events/blob/master/api/event-source.md#argoproj.io/v1alpha1.GithubEventSource
