### ISSUE TITLE
Trigger inputs

### ISSUE THREAD

**Issue by VaibhavPage** [argoproj/argo-events#19]
**Is your feature request related to a problem? Please describe.**
Currently sensor lacks the way of passing payload obtained from signal to triggers.

**Describe the solution you'd like**

**Comment by magaldima** [comment]
I've added a `LatestEvent` to the `NodeStatus` that contains the most recent `Event` for a certain signal node. This is done in #36 .

**Comment by magaldima** [comment]
We still should add a field to the sensor spec to specify `arguments` or `parameters` that we are passing to the trigger. By default, I think we should be passing the latest Event which is now stored in the sensor status. These args or params should be in addition to the latestEvent. This may also involve creating a `Triggerer` interface similarly to the `Signaler` interface which takes in an `Event` and other params/args.

**Comment by vicaire** [comment]
Will the whole payload necessarily be passed to the workflow? Or will this allow the user to extract a field from the payload? 

For instance, let us assume that the event is that a file was added to GCS (which triggers either a webhook notification, or a new message in a pub/sub queue). 

Could the solution let the user specify that the name of the GCS object should be extracted from the pub/sub message json content, and then passed to the Argo workflow as the value for the parameter "OBJECT_URI"?

**Comment by magaldima** [comment]
Ideally, the entire payload shouldn't be passed to the workflow. However, the entire payload should be passed to a Trigger to allow extracting only certain desired content fields. In order to do this, you need to either specify a direct JSON field name or use some sort of regex matching in the sensor spec which implies you know the shape of the JSON content before you create the sensor (a totally reasonable assumption). 

The idea of then passing to the Argo Workflow is a bit trickier. Right now, triggers are fairly generic and can support any number of k8s resources. Passing a parameter to the workflow requires modifying the workflow in memory before creation. We should probably create a workflow specific trigger so that this is an easier problem to solve and we can integrate tighter with the existing `argo` platform. This will also more clearly define the RBAC roles for `argo-events`. Later, we can think about adding back functionality for different types of triggers.

**Comment by vicaire** [comment]
magaldima@, the plan that you described looks good to me. Thanks!

**Comment by magaldima** [comment]
this is more clearly defined/addressed in #50
