### ISSUE TITLE
Deleted Pod of Gateway/Sensor is not Noticed

### ISSUE THREAD

**Issue by dtaniwaki** [argoproj/argo-events#194]
**Is your feature request related to a problem? Please describe.**

If a pod of a gateway/sensor is deleted accidentally or purposely, there's no way to know about it even in controller's log.

**Describe the solution you'd like**

We should use deployments instead of pods, or at least, we should watch created pods and update the state of gateways/sensors.

**Describe alternatives you've considered**

N/A

**Additional context**

It seems a deployment is created for gateway/sensor before this refactoring.
https://github.com/argoproj/argo-events/pull/148
Could you share the context of why we changed it like so?

**Comment by dtaniwaki** [comment]
I'm happy to implement it after discussing the best solution for this.

**Comment by VaibhavPage** [comment]
I guess although deployment helps in scenarios where pods are mistakenly deleted, it doesn't help much if an error occurs in pod and pod crashes. 

I am inclining towards monitoring pod from the controller. It would address scenarios like If a pod gets deleted mistakenly, we can check if the resource exists and is in new/running state and create a new pod but also If an unexpected crash occurs, we can log the error in the controller's output and recreate the pod. The monitoring would extend further in the controller's `operate` method. Right now, when a controller picks up a resource that is already in `error` mode, it doesn't perform any analysis like if the resource has been updated after it went in the error state and whether the updates are applied to the pod.

**Comment by magaldima** [comment]
Thanks for raising this @dtaniwaki . I agree with @VaibhavPage on this one. I think having each respective controller also monitor changes to the pods should be a reasonable. I believe the main argo workflow controller implements a simple solution for this where a pod watcher re-queues the associated custom resource onto the queue. 

Also, @VaibhavPage I'm curious as well why #148 changed gateways from deployments to pods. Can you shed some more light on this?

**Comment by VaibhavPage** [comment]
@magaldima the reason was if an unexpected crash occurred in gateway, the deployment used to bring the pod up again to maintain replica of 1 and it would go into CrashLoopBackOff. Also changing the gateway spec to address the error had no effect on deployment as it wasn't handled in controller code. So having gateway deployed as deployment had no real advantage.

**Comment by magaldima** [comment]
So does this enhancement for watching associated pods make sense for `gateways` and/or `sensors`?

**Comment by VaibhavPage** [comment]
Yeah, it would make sense. It will give the user a chance to update the gateway/sensor resource and retry.
Because once the user updates either gateway/sensor resource that is in error, we can delete the crashed pod and redeploy the pod with the updated spec.  The controller will have a default retry strategy for gateway/sensor. But the user can override it in the gateway/sensor spec. So that error related image pull, wrong env vars, configmaps, secrets, mounted volumes etc can be corrected by the user without deleting the resource and recreating.

**Comment by dtaniwaki** [comment]
Makes sense. I will find a time this week and will try to implement it. :)

**Comment by davidboren** [comment]
+1 from me as well.  We have an autoscaling cluster on top of ec2 instances, so our propensity to "roll" resources is increased.  So currently I will occasionally lose the long-running cronjob sensor pods due to normal cluster node turnover, and, because they have no deployment/replicaset backing, they never come back up and it's necessary for me to recreate the sensors themselves.

**Comment by VaibhavPage** [comment]
@dtaniwaki let me know if you want to me work on parts of the issue. We can divide it into two parts, one for gateway controller and other for sensor ctrl. Basically, we are planning to address this issue before we go 1.0

**Comment by VaibhavPage** [comment]
Also should we requeue the resource object if the service created gets deleted?

**Comment by dtaniwaki** [comment]
@VaibhavPage
Thank you for your help, but I’m implementing the following functions right now and they’re almost done. 
- recreating pod and service for gateways
- recreating pod for sensors
- updating changed pod and service spec for gateways
- updating changed pod spec for sensors

I’ll create a PR today or tomorrow. Is there any missing functions?

**Comment by VaibhavPage** [comment]
Nice!!! one more thing we should address is sensor service(which is ClusterIP service) that is created if the `eventProtocol` is HTTP. Most users use `eventProtocol` HTTP instead of NATS

**Comment by nstott** [comment]
Looking forward to this improvement, thanks!

How robust will the delivery of events be in the case of sensor/gateway pods crashing.
If a pod gets deleted as it's processing a message, what are the delivery guarantees of the event?

**Comment by VaibhavPage** [comment]
@nstott in terms of event guarantees, it depends upon the protocol you use to dispatch events from gateway to sensor, either HTTP or NATS(standard/streaming)(https://nats.io/documentation/streaming/nats-streaming-intro/). With HTTP, basically, there are no guarantees on the delivery of events.  If you are looking for at least once guarantee, then using `eventProtocol` as NATS streaming would be a fit solution. In addition, you can replay the events by storing them on a persistent volume. Take a look at NATS configuration you can add in sensor spec. https://github.com/argoproj/argo-events/blob/d1c812099e086de37dd77160228dc360c27d4dff/pkg/apis/common/event.go#L117

In terms of gateway crash, I think we should implement an `EventStore` interface that basically stores the events as soon as a gateway receives them from the outside entity. So that a user can replay them later. This will address #4 as well.

**Comment by magaldima** [comment]
A future, most likely v2, feature will be an additional CRD + controller that abstracts the concept of a PubSub queue or channel and which is used to ensure event delivery guarantees. As @VaibhavPage pointed out, for now this depends on your actual implementation, but in the future, this should be an out of the box feature of argo-events.

**Comment by dtaniwaki** [comment]
I finished the implementation. I’m writing unit tests right now...

**Comment by VaibhavPage** [comment]
#208
