### ISSUE TITLE
Expose prometheus metrics in sensors and eventsources

### ISSUE THREAD

**Issue by nstott** [argoproj/argo-events#204]
It's useful to be able to monitor argo by collecting and analyzing prometheus metrics.  I can alert on failed  workflows easily. I can track activity over time, etc.

I would like to be able to do the same within argo-events.  monitor the system for successes, failures, etc.

for example, if I am using a trigger with a remote source (git|http|s3|etc) in a sensor, it would be useful to emit a metric when there's a failure to fetch this.  right now these types of errors are difficult to catch

**Comment by VaibhavPage** [comment]
Thanks for creating the issue. I agree that it is essential to expose the Prometheus metrics.

**Comment by VaibhavPage** [comment]
This issue will be addressed after v1.0

**Comment by LegNeato** [comment]
Has there been movement here? Any pointers to implementation details if I wanted to take a crack at this?

**Comment by VaibhavPage** [comment]
You can refer https://github.com/argoproj/argo/tree/master/workflow/metrics

**Comment by alexec** [comment]
Would anyone like to take this on? My first thought is that metrics for the controllers would be easy, but that does not catch the errors you care about (failed messages). This only appears in the logs today. So the sensor controller needs metrics, and  because these can come and go, it is important that we use Prometheus service discovery to find them:

https://blog.sebastian-daschner.com/entries/prometheus-kubernetes-discovery
