### ISSUE TITLE
Add e2e tests

### ISSUE THREAD

**Issue by dtaniwaki** [argoproj/argo-events#233]
**Is your feature request related to a problem? Please describe.**

N/A

**Describe the solution you'd like**

We need some e2e test for basic cases to keep the quality.

**Describe alternatives you've considered**

N/A

**Additional context**

Maybe, we can use https://github.com/kubernetes-sigs/kind for the test.

**Comment by dtaniwaki** [comment]
@VaibhavPage If you agree with the necessity, I'll try to make it. What do you think?

**Comment by VaibhavPage** [comment]
Completely agree.

**Comment by monsiper** [comment]
This is a much needed feature. After adding this, can you also indicate the latest stable version somewhere because every time gateway/sensor spec format changes, something else breaks and I find myself reverting to one of the older versions. For example, Gateway spec from the latest image(0.8.3) is giving missing deploySpec error after deploying a gateway object.

**Comment by VaibhavPage** [comment]
v0.8.3 is the stable version. Although the spec has changed a bit for v0.8.3, check out the examples in master branch. We will be releasing v1.0 in the next few days.

**Comment by VaibhavPage** [comment]
#249
