### ISSUE TITLE
Make RouteConfig interface and stop using RouteConfig.Configs for keeping gw state

### ISSUE THREAD

**Issue by discordianfish** [argoproj/argo-events#239]
Just an idea, maybe there are reasons for things to be like they are or things won't work as I imaging.

I think RouteConfig should be made an interface, e.g ProcessRoute should take an interface instead of the RouteConfig struct. That would allow gateways to use their own struct that implements the interface to keep state.

This would make the gateways less brittle since it removes the need for casting interfaces for configs etc.

**Comment by VaibhavPage** [comment]
I agree that we should have `RouteConfig` as interface and stuffing things in `Configs` map was not the correct way. I guess it was because few functions have direct dependency on members of `RouteConfig` and it was easy to pass it as struct and just access the members. 

Let me create a pr to address this issue.

**Comment by VaibhavPage** [comment]
#243
