### ISSUE TITLE
Consistent versioned examples

### ISSUE THREAD

**Issue by magaldima** [argoproj/argo-events#244]
**Is your feature request related to a problem? Please describe.**
Discrepancies between the examples and certain release versions are causing lots of issues for people. This makes it extremely difficult to develop when there are breaking changes and is especially cumbersome because the gateway configs live in an unstructured `ConfigMap` instead of a versioned API. 

**Describe the solution you'd like**
My proposal is to build an automated test suite that scans over all folders in the examples to ensure they adhere to the requirements for each specific gateway/sensor configuration. In addition, I would like to move all the `community` gateways out of tree into a separate repo along with the change to make all the configurations live as a versioned `EventSource` CRD. This must be a requirement to achieve stability.

**Describe alternatives you've considered**
Let's start with a simple script that scans the examples and validates them against some structured API. This can be for all objects involved: Gateways, Sensor, and the gateway config maps. 

**Additional context**

**Comment by VaibhavPage** [comment]
I agree with your proposal. We already have a validation test that basically scans the example folders and validate gateway and sensor spec/configuration. But what we lack is test for gateway configmaps as there is no single validate method (This is where EventSource CRD will be helpful). 

Moving out community gateways into a separate repo (maybe something called `argo-events-gateways`) should be a priority as well. 

My proposal is to get #225 merged with suggested changes, drop the v0.9 tag so that it will resolve any outstanding patch confusions and work towards `EventSource CRD` for v1.0

**Comment by VaibhavPage** [comment]
@spk83 @dtaniwaki thoughts?

**Comment by dtaniwaki** [comment]
I agree with it too. I’m going to implement e2e tests for basic cases and will make it usable for community gateway tests, maybe by using the examples.

**Comment by VaibhavPage** [comment]
#251
