### ISSUE TITLE
sarama library for Kafka no longer supported

### ISSUE THREAD

**Issue by tooptoop4** [argoproj/argo-events#2554]
see https://github.com/Shopify/sarama/issues/2461

https://github.com/segmentio/kafka-go could be an option

**Comment by whynowy** [comment]
@tooptoop4 - thanks!

**Comment by dnwe** [comment]
I wouldn't necessarily suggest that Spotify is suddenly "no longer supported" as there hasn't really been any direct involvement from Spotify since bai left and it's continued to be maintained on an adhoc basis by myself and 3rd party contributors. The new GH issue is simply their team making that stance public and suggesting a new GitHub org should own the project going forward.

Aside, if you were planning to look at migration anyway, I'd suggest https://github.com/twmb/franz-go by @twmb / Redpanda team is the best alternative option for a kafka client

**Comment by OneCricketeer** [comment]
Can this be closed? IBM is taking over sarama maintenance
