### ISSUE TITLE
Sensor not able to connect kafka

### ISSUE THREAD

**Issue by slice-anuj** [argoproj/argo-events#2654]
**Describe the bug**
Sensor not able connect to kafka event bus
```
2023-06-12T13:08:29.165Z	INFO	argo-events.sensor	cmd/start.go:84	starting sensor server	{"sensorName": "github-branch", "version": "v1.8.0"}
2023-06-12T13:08:29.165Z	INFO	argo-events.sensor	metrics/metrics.go:175	starting metrics server	{"sensorName": "github-branch"}
2023-06-12T13:09:01.875Z	FATAL	argo-events.sensor	cmd/start.go:87	failed to listen to events	{"sensorName": "github-branch", "error": "failed after retries: kafka server: Transactional ID authorization failed"}
github.com/argoproj/argo-events/sensors/cmd.Start
	/home/runner/work/argo-events/argo-events/sensors/cmd/start.go:87
github.com/argoproj/argo-events/cmd/commands.NewSensorCommand.func1
	/home/runner/work/argo-events/argo-events/cmd/commands/sensor.go:14
github.com/spf13/cobra.(*Command).execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944
github.com/spf13/cobra.(*Command).ExecuteC
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068
github.com/spf13/cobra.(*Command).Execute
	/home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
github.com/argoproj/argo-events/cmd/commands.Execute
	/home/runner/work/argo-events/argo-events/cmd/commands/root.go:19
main.main
	/home/runner/work/argo-events/argo-events/cmd/main.go:8
runtime.main
	/opt/hostedtoolcache/go/1.20.3/x64/src/runtime/proc.go:250
```

**Environment:**
 - Kubernetes: [v1.25]
 - Argo: [v2.7.4]
 - Argo Events: [v1.8.0]
---

**Comment by gyanprakash48** [comment]
i am also facing this error , but when exploring a bit further , i manage to make it work by giving transactional ID permission on "*" scope. Question is how to make this work , when only  a prefix scope role is granted  ie transaction permission is given on "test.*"  scope .. i don't find any config to set that

**Comment by gyanprakash48** [comment]
@dfarr  i am hoping, you could give us a quick hint ? regarding setting this  transaction scope ?

**Comment by dfarr** [comment]
A Sensor wired up to a kafka eventbus does require permission to perform kafka transactions. I am not familiar with this ACL authorization, but I do know set the producer transaction id to the pod name [here](https://github.com/argoproj/argo-events/blob/master/eventbus/kafka/sensor/kafka_sensor.go#L112-L113) (the hostname variable is set to the pod name [here](https://github.com/argoproj/argo-events/blob/master/sensors/cmd/start.go#L68-L71)).

I'm wondering if you can set the authorization scope to something like `my-sensor-*` where the prefix is the known part of the pod name?

**Comment by gyanprakash48** [comment]
@dfarr  thanks for your feedback. Indeed it worked  👍  .  i set the sensor name matching expected transaction scope pattern  and it is working fine now. 

Though it would be still nice, if this  can be made available as config that we can set in sensor yaml defintion.  Specially because sensor name is used to generate below three topic.  i am not sure if  still it make sense to keep this ticket open..

event | {spec.kafka.topic}
trigger | {spec.kafka.topic}-{sensor-name}-trigger
action | {spec.kafka.topic}-{sensor-name}-action

**Comment by dfarr** [comment]
Are you looking for the ability to specify topic names in the config or producer ids? The producer ids need to be unique per producer, so the pod name is a good candidate, however, we could specify an optional prefix. This would help with defining the authorization scope on the kafka ACL side.

**Comment by gyanprakash48** [comment]
@dfarr  i agree,  pod name is a  really good candidate .  But Pod name is  prefixed  based on  sensor name, and sensor name is part of trigger and action Kafka topic.  

Here  is how it looks in my case, to give you an idea ..

my Kafka user has access on  Kafka  topics with prefix  " test.workflow.*"   and transaction scope  " test.workflow.*"

In order to match the transaction scope ,
i named  my  sensor = test.workflow.KafkaSensor  

i created a  Kafka event bus topic  =  test.workflow.KafkaEventBus

so it expect action and trigger topic as 

trigger  (topic) =  test.workflow.KafkaEventBus-test.workflow.KafkaSensor-trigger
Action (topic) = test.workflow.KafkaEventBus-test.workflow.KafkaSensor-action

you can see trigger and Action topic name , becoming weird .

What would be nice, either trigger and  Action topic  are allowed to set  by user,  or 
allowing to set producer transaction id prefix

**Comment by dfarr** [comment]
Those names are quite verbose, but correct. Multiple sensors can be wired up to the same eventbus so we need to ensure that the trigger and action topics are unique per sensor. I feel the best solution would be to add an optional prefix to the producer id, this prefix could be set in the sensor spec. This would maintain backwards compatibility for anyone who is dependent on the current naming convention while still resolving the issue you are experiencing.


```
config.Producer.Transaction.ID = s.optionalPrefix + s.hostname // s.optionalPrefix == "" if not set
```

@gyanprakash48 what are your thoughts?

**Comment by gyanprakash48** [comment]
Sounds good @dfarr  . This solution will do the job.
