### ISSUE TITLE
How to avoid retriggering an in-progress workflow

### ISSUE THREAD

**Issue by thundergolfer** [argoproj/argo-events#310]
**Is your feature request related to a problem? Please describe.**

We are using Argo-Events to schedule workflows at certain times. These workflows are batch jobs, and some shouldn't have >1 instance of the job running at one time. 

For example, we have a job that we schedule every 3 hours. At 13:00 the job gets scheduled. If at 16:00 the job hasn't finished we don't want to re-trigger the job again until the first has finished. 

Is there a way to support this in Argo-Events? I haven't been able to figure it out as yet.

**Comment by VaibhavPage** [comment]
This is not supported right now but could be a new feature for next release.

**Comment by thundergolfer** [comment]
Ahh thanks for letting me know. I saw the within-workflow `parallelism` limit and the global/system parallel workflow limit, and was hoping I was just not looking at the right docs. 

What makes the difference between "could" and "will"?  Should I hope to see it added here -> https://github.com/argoproj/argo/blob/master/ROADMAP.md? 

Cheers.

**Comment by groodt** [comment]
@thundergolfer Individual workflows can already control their own concurrency by acquiring / releasing locks as part of the workflow itself through an external locking service if exactly once triggering is necessary.

Otherwise, how would a specific "logical" workflow be identified? I don't think it can be done purely by `name` in a generic fashion. `Workflows` are simply k8s CRDs after all. Argo doesn't have a concept of "logical" Workflow across versions. They are either singletons with a fixed name that doesn't permit duplicates, or unique instances with `generateName` that run everytime like the native k8s CronJobs.
