### ISSUE TITLE
Gateway pod restart brake argo-events

### ISSUE THREAD

**Issue by Erik-Securenative** [argoproj/argo-events#494]
argo-events version 12
all is running ok 
once you delete the gateway pod and try to send event you get 

WARN[2020-02-17 11:57:07] unable to send event. no client found for the subscriber  subscriber="http://github-sensor.argo-events.svc:9300/"
INFO[2020-02-17 11:57:07] dispatched event. although some of the dispatch operations failed, check logs for more info  event-source=XXX
INFO[2020-02-17 11:57:14] dispatching event to subscribers              event-source=XXX

now if you add something to events source you see reload in log and its back to work

**Comment by VaibhavPage** [comment]
The gateway looks for the `subscribers` available in the gateway resource and it is not related to the event sources. It may be due to the gateway resource updates for subscribers were not captured correctly in the v0.12. The fix is now available in the master branch https://github.com/argoproj/argo-events/blob/master/gateways/client/client.go#L66 and I will release the patch asap.

**Comment by Erik-Securenative** [comment]
0.12.1 fix the issue
