### ISSUE TITLE
extensible signal interface

### ISSUE THREAD

**Issue by magaldima** [argoproj/argo-events#8]
**Is your feature request related to a problem? Please describe.**
Users of Axis cannot be assumed to use the same signals as implemented in this project. Conversely, in order to maintain usefulness & extensibility, we would need to keep adding new signal types and sources, greatly adding to the complexity of the project.

**Describe the solution you'd like**
I suggest a containerized interface for signals. Each signal executor is essentially a packaged image that implements a signal interface. Executors could send events defined as `CloudEvent` protos via `gRPC` to the host controller. These executors would still get deployed within the sensor controller and monitored during lifecycle of a sensor. The advantages being we can still leverage K8s jobs + pods for resiliency and scheduling and we can become extensible to be able to support any type of signal combination. There are two problems with this approach. 
1. How do we ensure the executor implements the signal interface and doesn't just execute any arbitrary code?
2. How do we define any extensible signal via a `Sensor` specification CRD? Will this entail hardcoded fields such as `url` and `key` and flexible fields such as maps to store additional information about that signal specification?

**Describe alternatives you've considered**
An alternative would be to define Axis as a library. The downside here is that the library itself would need to be tied very closely with Kubernetes and the Kube API.

**Comment by VaibhavPage** [comment]
@magaldima Thinking about making events as CRD,

1) As soon as signal receives the event, we create a CRD with appropriate labels.

2) Once all signals are resolved, we create and "watch" the  trigger. As soon as trigger resource successfully completes, we mark associated Event CRDs as complete and delete them(we may provide option to store them in a datastore like ElasticSearch) (Drawback here is what if the trigger is not a Kubernetes resource then how to make sure it completed). Deleting event CRDs as soon as trigger resource completes prevents us from having useless event CRDs.

3) In case a sensor dies(for any reason whatsoever) in middle of execution, we already have the events received as CRDs. So when user recreates that sensor, we provide an option whether to replay all events associated with that sensor or cherry pick the events.
 
4) Also we can have a vacuum process just how Brigade has it to clear the old events CRD. 

Looking at Brigade.js, they are considering making events as CRD. 

`Brigade events are currently specified as Kubernetes Secrets with particular labels. We use secrets because at the time of development, Third Party Resources were deprecated and Custom Resource Descriptions are not final. This aspect of the system may change between the 0.1.0 release of Brigade and the 1.0.0 release.`

Also I am wondering whether we should have a sensor gateway similar to Brigade gateway, although I am not sure how that fits with our architecture.

**Comment by magaldima** [comment]
Your idea treats Events as standalone structured units of data not attached to any particular controller. According to the Kubernetes documentation: `On their own, custom resources simply let you store and retrieve structured data. It is only when combined with a controller that they become a true declarative API.` Thus, I believe promoting events to a CRD is overkill as we would not have a controller matching the actual state of the event with the expected state. Also, do we want `Events` to be readable and writable by `kubectl`?

For Brigade and other platforms, having Events as a CRD may make sense if a single event fires a single action and the controller just operates on the events. This is nice because then, extending event sources is easy (they just need to be like Brigade gateways). We could have gone this route as well, but we need to be able to support multi-dependent triggers. A true declarative Event API would not be able to support this feature.
