### ISSUE TITLE
Workflows has no status and no age

### ISSUE THREAD

**Issue by ucloud-lee** [argoproj/argo-events#922]
# Summary

My workflows has no status and no age?

# Motivation

Who can help me? 
![image](https://user-images.githubusercontent.com/67354376/96686334-faedea80-13b0-11eb-84ae-3ff4eb7df877.png)

**Comment by whynowy** [comment]
What happens when you create a workflow directly in the same namespace?

**Comment by vvvlad** [comment]
We had this issue when argo workflow was installed in namespace a but running demo in namespace b.
In addition to it, sensors need to have instanceid pointing to workflow namespace (even when they share it).

**Comment by whynowy** [comment]
Sorry for the late response.

I think this is expected.

- If your workflow-controller is installed in namespace mode, then you need to make sure the sensor created workflow is in the namespace that workflow-controller watches.
 
- If your workflow is installed cluster wide, it should be ok.

No matter which mode your workflow-controller is installed, if `instance-id` is used, then the workflow that sensor created should have the same `instance-id`, otherwise it won't be processed by the workflow-controller.

**Comment by whynowy** [comment]
Let me know if you still have questions.
