### ISSUE TITLE
ArgoEvents should retry messages that could not be processed by sensors

### ISSUE THREAD

**Issue by JonathanSerafini** [argoproj/argo-events#948]
**Is your feature request related to a problem? Please describe.**
When an error is returned by a trigger ( ex.: Unavailable from CustomTrigger ), messages are not re-attempted and are simply dropped. 

**Describe the solution you'd like**
Ideally messages should be re-queued into the eventbus, or simply not ACKed if they have not been processed successfully. There could optionally be an option to configure retry logic or a standard interface for sensors to request a retry.

**Describe alternatives you've considered**
Can't really think of any alternative solutions right now, it seems to be pretty deep in the argo flow.
https://github.com/argoproj/argo-events/blob/ab7506d2b020b5c5a3aa0ca54e0776d2c4b4279c/sensors/listener.go#L147 simply doesn't do anything with errors. 

**Additional context**

---

**Message from the maintainers**:

If you wish to see this enhancement implemented please add a 👍 reaction to this issue! We often sort issues this way to know what to prioritize.

**Comment by whynowy** [comment]
👍 , thanks for raising this issue, yes, we definitely need to have some kind of mechanism for retry,  it might be better to give the option to user instead of simply retrying, because we actually don't know if there's any impact of retrying - say you have multiple steps in the action, and it failed at the 1st one.


#984

**Comment by whynowy** [comment]
https://github.com/argoproj/argo-events/pull/1090
